//
//  PythonScript.swift
//  Terrarium
//
//  Created by Claude Code on 2026-02-01.
//

import Foundation

/// A saved Python script.
public struct PythonScript: Identifiable, Codable, Equatable, Hashable {
    /// Unique identifier for the script.
    public let id: UUID

    /// Display name of the script.
    public var name: String

    /// The Python source code.
    public var code: String

    /// Optional description of what the script does.
    public var description: String?

    /// When the script was created.
    public let createdAt: Date

    /// When the script was last modified.
    public var modifiedAt: Date

    /// When the script was last executed.
    public var lastExecutedAt: Date?

    /// The result of the last execution.
    public var lastResult: LastExecutionResult?

    /// Tags for organizing scripts.
    public var tags: [String]

    /// Whether this script was generated by AI.
    public var isAIGenerated: Bool

    /// The file URL where this script is stored.
    public var fileURL: URL?

    public init(
        id: UUID = UUID(),
        name: String,
        code: String,
        description: String? = nil,
        createdAt: Date = Date(),
        modifiedAt: Date = Date(),
        lastExecutedAt: Date? = nil,
        lastResult: LastExecutionResult? = nil,
        tags: [String] = [],
        isAIGenerated: Bool = false,
        fileURL: URL? = nil
    ) {
        self.id = id
        self.name = name
        self.code = code
        self.description = description
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.lastExecutedAt = lastExecutedAt
        self.lastResult = lastResult
        self.tags = tags
        self.isAIGenerated = isAIGenerated
        self.fileURL = fileURL
    }
}

/// Summary of the last execution result (stored with the script).
public struct LastExecutionResult: Codable, Equatable, Hashable {
    public let exitCode: Int
    public let success: Bool
    public let durationMs: Int
    public let timestamp: Date
    public let outputPreview: String?

    public init(from result: PythonRunResult) {
        self.exitCode = result.exitCode
        self.success = result.isSuccess
        self.durationMs = result.durationMs
        self.timestamp = Date()

        // Store a preview of the output (first 500 chars)
        let output = result.combinedOutput
        if output.count > 500 {
            self.outputPreview = String(output.prefix(500)) + "..."
        } else {
            self.outputPreview = output.isEmpty ? nil : output
        }
    }
}
