//
//  PythonScriptManager.swift
//  Terrarium
//
//  Created by Claude Code on 2026-02-01.
//

import Foundation
import Combine

/// Manages Python script storage, loading, and organization.
@MainActor
public final class PythonScriptManager: ObservableObject {

    // MARK: - Published State

    @Published public private(set) var scripts: [PythonScript] = []
    @Published public private(set) var isLoading: Bool = false
    @Published public private(set) var lastError: PythonError?

    // MARK: - Properties

    private let configuration: PythonConfiguration
    private let fileManager = FileManager.default
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()

    // MARK: - Initialization

    public init(configuration: PythonConfiguration) {
        self.configuration = configuration
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        decoder.dateDecodingStrategy = .iso8601
    }

    // MARK: - Loading

    /// Load all saved scripts from disk.
    public func loadScripts() async {
        isLoading = true
        defer { isLoading = false }

        do {
            let metadataURL = configuration.metadataFile

            guard fileManager.fileExists(atPath: metadataURL.path) else {
                scripts = []
                return
            }

            let data = try Data(contentsOf: metadataURL)
            let metadata = try decoder.decode(ScriptsMetadata.self, from: data)
            scripts = metadata.scripts
            lastError = nil
        } catch {
            lastError = PythonError.scriptReadFailed(error.localizedDescription)
            scripts = []
        }
    }

    /// Save all scripts to disk.
    private func saveScripts() async throws {
        let metadata = ScriptsMetadata(scripts: scripts, lastModified: Date())
        let data = try encoder.encode(metadata)
        try data.write(to: configuration.metadataFile)
    }

    // MARK: - CRUD Operations

    /// Create a new script.
    @discardableResult
    public func createScript(name: String, code: String, description: String? = nil) async throws -> PythonScript {
        let script = PythonScript(
            name: name,
            code: code,
            description: description,
            isAIGenerated: false
        )

        // Save the Python file
        let fileURL = try await saveScriptFile(script)

        var savedScript = script
        savedScript.fileURL = fileURL

        scripts.append(savedScript)
        try await saveScripts()

        return savedScript
    }

    /// Create a script that was generated by AI.
    @discardableResult
    public func createAIGeneratedScript(name: String, code: String, description: String?) async throws -> PythonScript {
        var script = PythonScript(
            name: name,
            code: code,
            description: description,
            isAIGenerated: true
        )

        let fileURL = try await saveScriptFile(script)
        script.fileURL = fileURL

        scripts.append(script)
        try await saveScripts()

        return script
    }

    /// Update an existing script.
    public func updateScript(_ script: PythonScript) async throws {
        guard let index = scripts.firstIndex(where: { $0.id == script.id }) else {
            throw PythonError.scriptNotFound(script.id)
        }

        var updatedScript = script
        updatedScript.modifiedAt = Date()

        // Update the file on disk
        let fileURL = try await saveScriptFile(updatedScript)
        updatedScript.fileURL = fileURL

        scripts[index] = updatedScript
        try await saveScripts()
    }

    /// Delete a script.
    public func deleteScript(id: UUID) async throws {
        guard let index = scripts.firstIndex(where: { $0.id == id }) else {
            throw PythonError.scriptNotFound(id)
        }

        let script = scripts[index]

        // Delete the file
        if let fileURL = script.fileURL {
            try? fileManager.removeItem(at: fileURL)
        }

        scripts.remove(at: index)
        try await saveScripts()
    }

    /// Record an execution result for a script.
    public func recordExecution(scriptId: UUID, result: PythonRunResult) async throws {
        guard let index = scripts.firstIndex(where: { $0.id == scriptId }) else {
            throw PythonError.scriptNotFound(scriptId)
        }

        scripts[index].lastExecutedAt = Date()
        scripts[index].lastResult = LastExecutionResult(from: result)
        try await saveScripts()
    }

    // MARK: - File Operations

    private func saveScriptFile(_ script: PythonScript) async throws -> URL {
        let fileName = sanitizeFileName(script.name) + ".py"
        let fileURL = configuration.scriptsDirectory.appendingPathComponent(fileName)

        // Add a header comment to the file
        let header = """
        # \(script.name)
        # ID: \(script.id)
        # Created: \(script.createdAt.ISO8601Format())
        # Generated by: \(script.isAIGenerated ? "AI" : "User")
        #
        # \(script.description ?? "No description")

        """

        let fullContent = header + script.code
        try fullContent.write(to: fileURL, atomically: true, encoding: .utf8)

        return fileURL
    }

    private func sanitizeFileName(_ name: String) -> String {
        // Remove invalid characters for file names
        let invalidCharacters = CharacterSet(charactersIn: "/\\:*?\"<>|")
        let sanitized = name.components(separatedBy: invalidCharacters).joined(separator: "_")
        return sanitized.isEmpty ? "unnamed_script" : sanitized
    }

    // MARK: - Search & Filter

    /// Search scripts by name or description.
    public func search(query: String) -> [PythonScript] {
        guard !query.isEmpty else { return scripts }

        let lowercasedQuery = query.lowercased()
        return scripts.filter { script in
            script.name.lowercased().contains(lowercasedQuery) ||
            (script.description?.lowercased().contains(lowercasedQuery) ?? false) ||
            script.code.lowercased().contains(lowercasedQuery)
        }
    }

    /// Filter scripts by tag.
    public func filter(byTag tag: String) -> [PythonScript] {
        scripts.filter { $0.tags.contains(tag) }
    }

    /// Get all unique tags.
    public var allTags: [String] {
        Array(Set(scripts.flatMap { $0.tags })).sorted()
    }

    /// Get AI-generated scripts.
    public var aiGeneratedScripts: [PythonScript] {
        scripts.filter { $0.isAIGenerated }
    }

    /// Get recently executed scripts.
    public var recentlyExecuted: [PythonScript] {
        scripts
            .filter { $0.lastExecutedAt != nil }
            .sorted { ($0.lastExecutedAt ?? .distantPast) > ($1.lastExecutedAt ?? .distantPast) }
    }
}

// MARK: - Metadata

private struct ScriptsMetadata: Codable {
    var scripts: [PythonScript]
    var lastModified: Date
}
